furnico-main/editp/urls.py
from django.urls import path
from . import views

from editp.views import *

app_name = 'editp'

urlpatterns = [
    path('admin_page/', views.admin_only_view, name='admin_page'),
    path('', views.edit_profile, name='edit_profile'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout')
]

furnico-main/furnico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('show_products.urls')),
    path('rating/', include('rating.urls')),
    # path('report/', include('report.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profile/', include('editp.urls')),
    path('article/', include('article.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furnico-main/show_products/urls.py
from django.urls import path
from show_products.views import *

app_name = 'show_products'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('edit_product/<str:id>', edit_product, name='edit_product'),
    path('edit_category/<str:id>', edit_category, name='edit_category'),
    path('delete_product/<str:id>', delete_product, name='delete_product'),
    path('delete_category/<str:id>', delete_category, name='delete_category'),
    path('product/<str:id>', show_product, name='show_product'),
    path('all_product', show_all_products, name='show_all_products'),
    path('all_product/<str:id>', show_category_products, name='show_category_products'),
    path('search/', search_products, name='search_products'),

    path('create_product_ajax', create_product_entry_ajax, name='create_product_entry_ajax'),
    path('create_category_ajax', create_category_ajax, name='create_category_ajax'),
    path('json_filtered/<str:id>/', show_json_filtered, name='show_json_filtered'),

    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json_cat/', show_json_cat, name='show_json_cat'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
]

furnico-main/wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('add-to-wishlist/<str:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove-wishlist/<str:product_id>/', remove_wishlist, name='remove_wishlist'),
    path('', wishlist_view, name='wishlist'),
    path('wishlist-json/', wishlist_json_view, name='wishlist_json'),
    path('create-collection/', create_collection, name='create_collection'),
    path('update-collection-name/<int:collection_id>/', update_collection_name, name='update_collection_name'),
    path('delete-collection/<int:collection_id>/', delete_collection, name='delete_collection'),
]

furnico-main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <script src="https://cdn.tailwindcss.com">
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

furnico-main/templates/navbar.html
<!-- component -->
{% load static %}

<header class="fixed top-0 left-0 w-full bg-white shadow-md z-50 p-4">
  <div class="container mx-auto px-4 py-2 flex items-center justify-between">

    <!-- logo -->
    <div class="mr-auto md:w-48 flex-shrink-0">
      <a href="{% url 'show_products:show_main' %}">
        <img src="{% static 'image/logo_furnico.png' %}" class="h-8 md:h-14" alt="">
      </a>
    </div>

    <!-- hamburger menu -->
    <div class="block md:hidden">
      <button id="menu-toggle" class="focus:outline-none">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>
    </div>

    <!-- search bar for larger screens -->
    <div class="hidden md:flex w-full max-w-xs xl:max-w-lg 2xl:max-w-2xl bg-gray-100 rounded-md items-center">
      <select class="bg-transparent uppercase font-bold text-sm p-4 mr-4" name="" id="categoryDropdown">
        <option value="{% url 'show_products:show_all_products' %}">Semua Kategori</option>
        {% for category in categories %}
        <option value="{% url 'show_products:show_category_products' category.pk %}">{{ category.category_name }}</option>
        {% endfor %}
      </select>
      <input class="border-l border-gray-300 bg-transparent font-semibold text-sm pl-4" type="text" id="search-input" placeholder="Saya mencari ..." oninput="searchProducts(this.value)">
      <svg class="ml-auto h-5 px-4 text-gray-500" aria-hidden="true" focusable="false" data-prefix="far" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-search fa-w-16 fa-9x">
        <path fill="currentColor" d="M508.5 468.9L387.1 347.5c-2.3-2.3-5.3-3.5-8.5-3.5h-13.2c31.5-36.5 50.6-84 50.6-136C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c52 0 99.5-19.1 136-50.6v13.2c0 3.2 1.3 6.2 3.5 8.5l121.4 121.4c4.7 4.7 12.3 4.7 17 0l22.6-22.6c4.7-4.7 4.7-12.3 0-17zM208 368c-88.4 0-160-71.6-160-160S119.6 48 208 48s160 71.6 160 160-71.6 160-160 160z"></path>
      </svg>
    </div>

    <!-- phone number -->
    <div class="ml-auto md:w-48 hidden sm:flex flex-col place-items-end">
      <span class="font-bold md:text-xl">0812 3456 7890</span>
      <span class="font-semibold text-sm text-gray-400">Support 24/7</span>
    </div>

    <!-- buttons -->
    <nav class="contents">
      <ul class="ml-4 xl:w-48 flex items-center justify-end">
        <li class="ml-2 lg:ml-4 relative inline-block">
          <a class="" href="{% url 'editp:edit_profile' %}">
            <svg class="h-9 lg:h-10 p-2 text-gray-500" aria-hidden="true" focusable="false" data-prefix="far" data-icon="user" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="svg-inline--fa fa-user fa-w-14 fa-9x">
              <path fill="currentColor" d="M313.6 304c-28.7 0-42.5 16-89.6 16-47.1 0-60.8-16-89.6-16C60.2 304 0 364.2 0 438.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-25.6c0-74.2-60.2-134.4-134.4-134.4zM400 464H48v-25.6c0-47.6 38.8-86.4 86.4-86.4 14.6 0 38.3 16 89.6 16 51.7 0 74.9-16 89.6-16 47.6 0 86.4 38.8 86.4 86.4V464zM224 288c79.5 0 144-64.5 144-144S303.5 0 224 0 80 64.5 80 144s64.5 144 144 144zm0-240c52.9 0 96 43.1 96 96s-43.1 96-96 96-96-43.1-96-96 43.1-96 96-96z"></path>
            </svg>
          </a>
        </li>
        <li class="ml-2 lg:ml-4 relative inline-block">
          <a class="" href="{% url 'wishlist:wishlist' %}">
            <svg class="h-9 lg:h-10 p-2 text-gray-500" aria-hidden="true" focusable="false" data-prefix="far" data-icon="heart" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-heart fa-w-16 fa-9x">
              <path fill="currentColor" d="M458.4 64.3C400.6 15.7 311.3 23 256 79.3 200.7 23 111.4 15.6 53.6 64.3-21.6 127.6-10.6 230.8 43 285.5l175.4 178.7c10 10.2 23.4 15.9 37.6 15.9 14.3 0 27.6-5.6 37.6-15.8L469 285.6c53.5-54.7 64.7-157.9-10.6-221.3zm-23.6 187.5L259.4 430.5c-2.4 2.4-4.4 2.4-6.8 0L77.2 251.8c-36.5-37.2-43.9-107.6 7.3-150.7 38.9-32.7 98.9-27.8 136.5 10.5l35 35.7 35-35.7c37.8-38.5 97.8-43.2 136.5-10.6 51.1 43.1 43.5 113.9 7.3 150.8z"></path>
            </svg>
          </a>
        </li>
        <li class="ml-2 lg:ml-4 relative inline-block">
          <a class="" href="{% url 'editp:logout' %}">
            <button class="px-6 py-2 bg-red-500 rounded-full hover:bg-red-700 text-white font-bold">
              Logout
            </button>
          </a>
        </li>
      </ul>
    </nav>
  </div>

  <!-- Search and Dropdown for Mobile -->
  <div id="mobile-menu" class="hidden md:hidden bg-gray-100">
    <div class="flex items-center justify-between px-4 py-2">
      <select class="bg-transparent uppercase font-bold text-sm p-4 mr-4" name="" id="mobile-categoryDropdown">
        <option value="{% url 'show_products:show_all_products' %}">semua kategori</option>
        {% for category in categories %}
        <option value="{% url 'show_products:show_category_products' category.pk %}">{{ category.category_name }}</option>
        {% endfor %}
      </select>
      <input class="border-l border-gray-300 bg-transparent font-semibold text-sm pl-4" type="text" id="mobile-search-input" placeholder="I'm searching for ..." oninput="searchProducts(this.value)">
      <svg class="ml-auto h-5 px-4 text-gray-500" aria-hidden="true" focusable="false" data-prefix="far" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-search fa-w-16 fa-9x">
        <path fill="currentColor" d="M508.5 468.9L387.1 347.5c-2.3-2.3-5.3-3.5-8.5-3.5h-13.2c31.5-36.5 50.6-84 50.6-136C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c52 0 99.5-19.1 136-50.6v13.2c0 3.2 1.3 6.2 3.5 8.5l121.4 121.4c4.7 4.7 12.3 4.7 17 0l22.6-22.6c4.7-4.7 4.7-12.3 0-17zM208 368c-88.4 0-160-71.6-160-160S119.6 48 208 48s160 71.6 160 160-71.6 160-160 160zM400 464H48v-25.6c0-47.6 38.8-86.4 86.4-86.4 14.6 0 38.3 16 89.6 16 51.7 0 74.9-16 89.6-16 47.6 0 86.4 38.8 86.4 86.4V464zM224 288c79.5 0 144-64.5 144-144S303.5 0 224 0 80 64.5 80 144s64.5 144 144 144zm0-240c52.9 0 96 43.1 96 96s-43.1 96-96 96-96-43.1-96-96 43.1-96 96-96z"></path>
      </svg>
    </div>
  </div>

</header>

<script>
  document.getElementById('mobile-categoryDropdown').addEventListener('change', function() {
    window.location.href = this.value;
  });

  document.getElementById('categoryDropdown').addEventListener('change', function() {
    window.location.href = this.value;
  });

  document.getElementById('menu-toggle').addEventListener('click', function() {
    const mobileMenu = document.getElementById('mobile-menu');
    mobileMenu.classList.toggle('hidden');
  });
</script>